services:
  starknet-agent-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - 3001:3001
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    environment:
      - NODE_ENV=production


